### PR TITLE
Migrate check 1 and 94 to Cloud API

### PR DESCRIPTION
**Pull request by bjoern-jueliger-sap**
Checks 1 and 94 re-implemented so that they can be imported into a SAP BTP cloud system. There's nothing particular about these two checks, we just have to start somewhere.

Since the new object types that encapsulate ATC checks in a cloud context are not yet supported in abapGit, the readme contains instructions how to manually create these objects so the checks are usable.

Note also that currently the interfaces implemented here - like IF_CI_ATC_CHECK - are gated behind a feature toggle, so this will not yet work in all cloud systems.

### CODE REVIEW

**Comment by larshp** [comment]
I've added some of the interfaces in https://github.com/abaplint/deps/pull/114, but they need more work

feel free to adjust the linter configuration

**Comment by bjoern-jueliger-sap** [comment]
> I've added some of the interfaces in [abaplint/deps#114](https://github.com/abaplint/deps/pull/114), but they need more work
> 
> feel free to adjust the linter configuration

I'd really like to get the linter running smoothly - what's missing to add the new interfaces fully to abaplint? Just exporting them via abapGit from an up-to-date system into the /deps/ci repo?

**Comment by larshp** [comment]
@D072189 if you like, join the abapGit slack channel, https://abapgit-slackinviter.herokuapp.com/, then we can talk about options there?

**Comment by larshp** [comment]
well, `cl_ci_atc_assistant_factory` is not released as such, do you know how I can list the "Released with Feature Toggle" objects in the ADT Project explorer?

I'm adding the steampunk API in https://github.com/abapedia/steampunk-2111-api

**Comment by bjoern-jueliger-sap** [comment]
> well, `cl_ci_atc_assistant_factory` is not released as such, do you know how I can list the "Released with Feature Toggle" objects in the ADT Project explorer?
> 
> I'm adding the steampunk API in https://github.com/abapedia/steampunk-2111-api

It should be listed under Released Objects in a system where the toggle is on. But maybe it's easier to just wait until 2202, where it almost certainly will be released normally.

**Comment by larshp** [comment]
dependencies are assumed to be okay, in this case there is a false positive syntax check, adding fix in https://github.com/abaplint/abaplint/pull/2288

**Comment by larshp** [comment]
try again, should be fewer errors now

**Comment by bjoern-jueliger-sap** [comment]
This is odd - the abaplint here on github doesn't seem to find the dependencies in /dep2, but locally in my VSCode it works with the current abaplint.json

**Comment by larshp** [comment]
hmm, I'll have a look sometime during the weekend

**Comment by larshp** [comment]
fixed

**Comment by larshp** [comment]
when the deps are released they will be part of https://blogs.sap.com/2022/01/03/steampunk-released-abap-api-first-draft-is-up/, if it all works out :)

**Comment by larshp** [comment]
cool, lets work from here, merging 😄

**Pull request merged**
